### PR TITLE
Check if address components are available before inserting into targets

### PR DESCRIPTION
**Pull request by jumichot**
Salut ! 

Sometimes you don't have any street number in the autocomplete address, so in the adress field you end up "undefined".

Never wrote any typescript, let me know if there is a better way to check that ;)

### CODE REVIEW

**Comment by guillaumebriday** [comment]
Thanks for the PR!

What about resetting the field with an empty string if the data is undefined?

For instance:
```js
if (this.hasRouteTarget) this.routeTarget.value = address.route || ''
```

**Comment by guillaumebriday** [comment]
cf: https://github.com/stimulus-components/stimulus-places-autocomplete/commit/8be637d7c39efd087f1b756cf710af1d63d71547

**Comment by jumichot** [comment]
> Thanks for the PR!
> 
> What about resetting the field with an empty string if the data is undefined?
> 
> For instance:
> 
> 
> if (this.hasRouteTarget) this.routeTarget.value = address.route || ''

Yep, that seems better 👍

**Comment by guillaumebriday** [comment]
Cool, it will be available in hours in the next release then 👍

**Comment by jumichot** [comment]
Great, thanks !

**Comment by guillaumebriday** [comment]
@jumichot https://github.com/stimulus-components/stimulus-places-autocomplete/releases/tag/v0.4.0

**Pull request closed without merging**
